name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $
      VERSION_NAME: 124
      VERSION_CODE: 29

    steps:
      - name: Extract commit message
        shell: bash
        run: |
          export VERSION_INFO=$(echo ${{ github.event.head_commit.message }} | rev | cut -d ' ' -f1)
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV
          echo $VERSION_INFO
