
name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $
      VERSION_NAME: 1.2.4
      VERSION_CODE: 29

      S3_BUCKET_URL: "s3://buildtest-1122"
      S3_URL: "https://buildtest-1122.s3.ap-northeast-2.amazonaws.com"

    steps:
      - name: Set Time Zone
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2


      - name: Copy files to S3 with the AWS CLI
        run: |
          find . -type f -name "*.apk" -exec cp '{}' $ \;
          aws s3 cp $ $/$/
