
name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $

    steps:
      - name: Extract commit message
        shell: bash
        run: |
          export VERSION_INFO=$(echo ${{ github.event.head_commit.message }} | rev
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV

          export VERSION_NAME=$(echo $VERSION_INFO | cut -d ' ' -f1 | rev)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

          export VERSION_CODE=$(echo $VERSION_INFO | cut -d ' ' -f2 | rev)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
