
name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $

    steps:
      - name: Extract commit message
        shell: bash
        run: |
          export VERSION_INFO=$(echo ${{ github.event.head_commit.message }} | rev | cut -d ' ' -f1 | rev)
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV

      - name: Slack Notification Start
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_ICON_EMOJI: ":bellhop_bell:"
          SLACK_TITLE: "빌드 시작 / 버전 : ${VERSION_INFO}"
          SLACK_USERNAME: "incoming-webhook"
          SLACK_CHANNEL: "#caro-monitoring-build-android"
          SLACK_COLOR: "#CCCCCC"
          SLACK_MESSAGE: "commit : ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
