name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $
      VERSION_NAME: 124
      VERSION_CODE: 29

    steps:
      - name: Extract commit message
        shell: bash
        run: |
          export BRANCH_RAW=$(echo ${{ github.event.head_commit.message }})
          echo "BRANCH_RAW=$BRANCH_RAW" >> $GITHUB_ENV
