
name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: $
      KEYSTORE_PASSWORD: $
      KEY_PASSWORD: $

    steps:
      - name: Extract commit message
        shell: bash
        run: |
          export VERSION_INFO=$(echo ${{ github.event.head_commit.message }} | rev | cut -d ' ' -f1 | rev)
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV
          
          export VERSION_NAME=$VERSION_INFO | cut -d '_' -f1
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

          export VERSION_CODE=$VERSION_INFO | cut -d '_' -f2
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: set APK name
        run: |
          export TEMP_APK_NAME="caro_version_${VERSION_INFO}.apk"
          echo "APK_NAME=$TEMP_APK_NAME" >> $GITHUB_ENV
      - uses: actions/checkout@v2
