name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          arch: x86_64
          working-directory: directory
          profile: Nexus 6
          script: ./gradlew connectedCheck